[package]
name = "simple_mock_helper"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
once_cell = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
clap = { version = "4", features = ["derive"] }
anyhow = "1"
rustc-demangle = "0.1"
chrono = "0.4"

[dev-dependencies]
ctor = "0.2"

[[bin]]
name = "smh_coverage"
path = "src/bin/smh_coverage.rs"

[[bin]]
name = "coverage_gen"
path = "src/bin/coverage_gen.rs"
