[package]
name = "simple-sqp"
version = "0.1.0"
edition = "2021"
description = "Simple Query and Persistence layer for Simple language"

[lints]
workspace = true

[dependencies]
# Core
simple-common = { path = "../common" }
simple-db = { path = "../db" }
tracing = "0.1"
thiserror = "1.0"

# Naming conventions
Inflector = "0.11"

[dev-dependencies]
tempfile = "3"
