[package]
name = "simple-native-loader"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
libloading = "0.8"
thiserror.workspace = true
simple-common = { path = "../common" }
simple-runtime = { path = "../runtime" }

[dev-dependencies]
tempfile = "3"
cc = "1"
