[package]
name = "ffi_io"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
glob = "0.3"
fs2 = "0.4"
memmap2 = "0.9"
dirs-next = "2.0"
